version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /app
    command: sh -c "npm run db:push && npm run db:seed && npm run build && npm run start"
    # command: sh -c "npm run dev" # <-- use this command for testing/db:push
    volumes:
      - app-node-cache:/root/.npm
      - ./src:/app/src
    ports:
      - 3000:3000
      - 5555:5555
    environment:
      # Mandatory variables
      - NEXTAUTH_URL=http://localhost # <-- provide the url of your app here
      - NEXTAUTH_SECRET=your-secret
      - DATABASE_URL=mysql://utkarsh:utkarsh@db/utkarsh

      # Optional variables
      - REDIS_URL=redis://cache:6379
      - NODE_ENV=production
      - NEXT_PUBLIC_CLIENTVAR=clientvar
    networks:
      internal:

  cache:
    image: redis:4
    restart: always
    volumes:
      - redis-prod:/data
    networks:
      default:
      internal:
  
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - app
    networks:
      default:
      internal:

volumes:
  app-node-cache:
  redis-prod:

networks:
  default:
  internal:
