version: "3.8"
services:
  app:
    image: buddylonglegs/utkarsh-webapp:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm run db:seed && npm run start"
    # command: sh -c "npm run dev" # <-- use this command for testing/db:push
    ports:
      - 3000:3000
      - 5555:5555
    environment:
      # Optional variables
      - DATABASE_URL=mysql://utkarsh:utkarsh@db/utkarsh
      - REDIS_URL=redis://cache:6379
      - NODE_ENV=production
      - NEXT_PUBLIC_CLIENTVAR=clientvar
    env_file:
      - .env
    networks:
      default:
      internal:
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 400M


volumes:
  app-node-cache:

networks:
  default:
  internal:
