version: "3.7"

services:

  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run dev
    volumes:
      - webapp-node-cache:/root/.npm
      - ./src:/app/src
    environment:
      - REDIS_URL=redis://cache:6379
      - NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=secret
    env_file:
      - .env.local
    ports:
      - 3000:3000
      - 4983:4983 # Drizzle studio
    networks:
      default:
      internal:

  cache:
    image: redis:4
    restart: always
    volumes:
      - redis:/data
    networks:
      internal:

volumes:
  webapp-node-cache:
  redis:


networks:
  default:
  internal:
