services:

  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run dev
    volumes:
      - webapp-node-cache:/root/.npm
      - ./src/:/app/src/
      - ./prisma:/app/prisma
      - ./public:/app/public
    environment:
      - DATABASE_URL=mysql://utkarsh:utkarsh@db/utkarsh
      - REDIS_URL=redis://cache:6379
      - NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=secret
      - S3_BUCKET_REGION=us-east-1
      - S3_BUCKET_NAME=utkarsh
      - S3_ENDPOINT=http://localstack:4566
      - S3_ACCESS_KEY=test
      - S3_SECRET_KEY=test
      - S3_PUBLIC_URL=http://localhost:4566/utkarsh
      - USE_AVIRAL=true
    
    env_file:
      - .env

    ports:
      - 3000:3000
      - 5555:5555 # Prisma studio
    depends_on:
      db:
        condition: service_healthy
    networks:
      default:
      internal:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: utkarsh
      MYSQL_DATABASE: utkarsh
      MYSQL_USER: utkarsh
      MYSQL_PASSWORD: utkarsh
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      internal:
      default:
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uutkarsh", "-putkarsh"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566-4583:4566-4583"
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - EDGE_PORT=4566
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - s3:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      internal:
      default:

volumes:
  mysql:
  webapp-node-cache:
  s3:


networks:
  default:
  internal:
